SELECT
	ugb.TITLE AS TITLE,
    ugb.BOARD_ID AS BOARD_ID,
    ugr.REPLY_ID AS REPLY_ID,
    ugr.WRITER_ID AS WRITER_ID,
	ugr.CONTENTS AS CONTENTS,
    DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
	USED_GOODS_BOARD ugb
INNER JOIN
	USED_GOODS_REPLY ugr
		ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE
	ugb.CREATED_DATE >= '2022-10-01'
    AND ugb.CREATED_DATE < '2022-11-01'
ORDER BY
	ugr.CREATED_DATE ASC,
    ugb.title ASC;